version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airconnect_backend_qa
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000
    networks:
      - airconnect_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - airconnect_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - airconnect_network

networks:
  airconnect_network:
    driver: bridge